# Generated by Django 4.1 on 2022-08-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
